### ISSUE TITLE
Can't import forms4

### ISSUE THREAD

**Issue by ertwro** [glutanimate/internal-references#7]
The addon is no longer available in the anki website, but I tried to build it from source and I couldn't import forms4 and insertlink. Is this broken beyond repair, what am I missing?

**Comment by glutanimate** [comment]
FWIW, this add-on was never published on GitHub, but I do plan on picking up development on it again soon.

As for building from source: Not sure if you're of this, but there are some ready-made builds available on the released page, albeit only for Anki 2.0.

Which target are you trying to build the source for? It sounds like you might be working with Anki 2.1/qt5 (which would explain why the forms 4 dir wasn't created). Right now only Anki 2.0 / qt4 is supported.

**Comment by ertwro** [comment]
Anki 2.1/qt5 but I've tried the release for the 2.0/qt4 and it works. It's funny how one can't fully transition to Anki2.1 just yet. I'll eagerly await for any change here. By the way, I love your sequence inserter addon. Thanks.
